SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'portal_transferencias'
    AND COLUMN_NAME = 'destinatario_email'
    AND CHARACTER_MAXIMUM_LENGTH < 1000
)
BEGIN
  ALTER TABLE dbo.portal_transferencias ALTER COLUMN destinatario_email NVARCHAR(1000) NULL;
END;

COMMIT TRANSACTION;
